{
    "name" : "Wakf Board Assessment",
    "version" : "1.0",
    "depends" : ['sale','account','base','wakf_registration'],
    "author" : "Novasoft Consultancy Services Pvt. Ltd.",
    'category' : 'Generic Modules/Others',
    "description": """Wakf Board - Assessment Module
    
    """,
    'website': 'http://www.novasoftindia.com',
    'data': ['BJ_assessment_view.xml',
             'BJ_search.xml',
             'BJ_slab_view.xml',
             'security/wakf_assessment_security.xml',
             'security/ir.model.access.csv',
             'invoice_inherit_view.xml',
             'new_assessment_view.xml',
             'revenue_recovery_view.xml',
             'sale_order_view.xml',
             'showcause_view.xml',
             'wakf_assessment_head_view.xml',
             'Arrear_list_view.xml',
             'wakf_assessment_view.xml',
             ],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': True,

}
